spring.application.name=minsk-booking-bot
bot.name=MyBookingByXD450_Bot
bot.token=8878967168:AAHzDUgaB8pxbTOBQmijY74WxLZ263LhID0

# Настройки подключения к PostgreSQL в Минске
spring.datasource.url=jdbc:postgresql://localhost:5432/bookingdb
spring.datasource.username=postgres
# Вставь сюда тот самый пароль, который ты указал в Шаге 2:
spring.datasource.password=admin321

# Драйвер базы данных
spring.datasource.driverClassName=org.postgresql.Driver

# Автоматически создавать и обновлять таблицы под наши Java-классы
spring.jpa.hibernate.ddl-auto=update
# Показывать в консоли VS Code SQL-запросы, которые Java шлет в базу (очень удобно для учебы!)
spring.jpa.show-sql=true

# Глобальный график работы салона (в часах)
business.work.start=8
business.work.end=20
# поставить 24 если круглосуточно

# ID пользователей Telegram, у которых будет доступ к админ-панели (через запятую)
business.admin.ids=5858194068,12345678,98765432

# Максимальное количество активных записей на ОДНУ и ту же услугу для одного клиента
business.max.bookings.per.service=2

# Рабочие дни недели (Пн, Вт, Ср, Чт, Пт — работаем, Сб, Вс — выходной)
business.work.days=1,1,1,1,1,0,0

